create view D_10EMP as select * from emp where deptno = 10;
select * from d10_emp;
create view dept_summary as select d.dname, min(e.sal) minsal, max(e.sal) maxsal, avg(e.sal) avgsal from dept d, emp e group by dname;
select * from dept_summary;
create or replace view emp_data as select * from emp where sal between 1000 and 2000 and mgr in (select empno from emp);
select * from emp_data;
create view restrict as select * from emp where ename = '&ename' and to_char(sysdate, 'hh24') between 9 and 17 and to_char(sysdate, 'd') between 2 and 7;
select * from restrict;
create view employees as select empno, ename, job, deptno from emp where deptno in (select deptno from dept);
select * from employees;
create or replace view emp_read as select job, min(sal) minsal, max(sal) maxsal from emp group by job with read only;
select * from emp_read;
create view vw_client_master as select client_no, name, address1, balance_due from client_master;
select * from vw_client_master;
insert into vw_client_master values ('C007', 'ANKUR', 'BALLY', 0);
select * from vw_client_master;
update vw_client_master set balance_due = 1300 where client_no = 'C007';
select * from vw_client_master;
delete from vw_client_master where client_no = 'C007';
select * from vw_client_master;
select * from client_master;
create view vw_sales_det as select so.order_no, so.order_date, sod.product_no, sod.qty_ordered, so.order_status from sales_order so inner join sales_order_details sod on so.order_no = sod.order_no where so.order_status = 'BackOrder';
select * from vw_sales_det;
insert into vw_sales_det values ('O19032', '15-JAN-97', 'P00032', 2, 'BackOrder');
select * from vw_sales_det;
update vw_sales_det set qty_ordered = 7 where order_no = 'O19002';
select * from vw_sales_det;
delete vw_sales_det where order_no = 'O19002';
select * from vw_sales_det;
drop view vw_sales_det;